### ISSUE TITLE
Getting error while installing helm chart 

### ISSUE THREAD

**Issue by ajeetgupt** [SumoLogic/sumologic-kubernetes-collection#1423]
I have defined the access key, secret key, and endpoint in values.yaml file. But when installing the chart pod is getting terminated. Below are the logs. 

```
kubectl logs -n sumologic pod/sumologic-sumologic-kubernetes-collection-sumologic-setup-tb9ct

Terraform  has been successfully initialized!
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Couldn't automatically create fields
You do not have enough field capacity to create the required fields automatically.
Please refer to https://help.sumologic.com/Manage/Fields to manually create the fields after you have removed unused fields to free up capacity.
sumologic_collector.collector: Importing from ID "kubernetes-sb"...
sumologic_collector.collector: Import prepared!
  Prepared sumologic_collector for import
sumologic_collector.collector: Refreshing state... [id=kubernetes-sb]

### Error: Cannot import non-existent remote object

While attempting to import an existing object to
sumologic_collector.collector, the provider detected that no object exists
with the given id. Only pre-existing objects can be imported; check that the
id is correct and that it is associated with the provider's configured region
or endpoint, or use "terraform apply" to create a new remote object for this
resource.

kubernetes_secret.sumologic_collection_secret: Importing from ID "sumologic/sumologic"...
kubernetes_secret.sumologic_collection_secret: Import prepared!
  Prepared kubernetes_secret for import
kubernetes_secret.sumologic_collection_secret: Refreshing state... [id=sumologic/sumologic]

### Error: Cannot import non-existent remote object

While attempting to import an existing object to
kubernetes_secret.sumologic_collection_secret, the provider detected that no
object exists with the given id. Only pre-existing objects can be imported;
check that the id is correct and that it is associated with the provider's
configured region or endpoint, or use "terraform apply" to create a new remote
object for this resource.

sumologic_collector.collector: Creating...

### Error: {
  "status" : 401,
  "id" : "BTVEL-Y95PT-RCQPS",
  "code" : "unauthorized",
  "message" : "Credential could not be verified."
}

  on resources.tf line 1, in resource "sumologic_collector" "collector":
   1: resource "sumologic_collector" "collector" {


Error during applying Terraform changes
```

**Comment by pmalek-sumo** [comment]
Hi @ajeetgupt 

Did you specify `sumologic.endpoint` and it matches the environment the credentials where created at?

Here's a table that might help with the above: https://help.sumologic.com/APIs/General-API-Information/Sumo-Logic-Endpoints-and-Firewall-Security

Did you by any chance swap `sumologic.accessId` with `sumologic.accessKey`?

**Comment by ajeetgupt** [comment]
I passed the values correctly and did cross-verification using kubectl describe command :-
kubectl describe pod -n sumologic sumologic-collection-sumologic-setup-8ppwm

 Environment:
      SUMOLOGIC_ACCESSID:   suxxxxxxxxxx3
      SUMOLOGIC_ACCESSKEY:  1pxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx9
      SUMOLOGIC_BASE_URL:   https://api.us2.sumologic.com/api/
      HTTP_PROXY:
      HTTPS_PROXY:
      NO_PROXY:             kubernetes.default.svc

Let me know if I am missing anything?

**Comment by pmalek-sumo** [comment]
Can you share your `values.yaml` with masked credentials?

**Comment by ajeetgupt** [comment]
values:
    sumologic:
      accessId: "suxxxxxxxxx3"
      accessKey: "1pxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx9"
      endpoint: "https://api.us2.sumologic.com/api"
      collectorName: "kubernetes-sb"
      clusterName: "kubernetes-sb"

**Comment by pmalek-sumo** [comment]
There are 2 more things that you can check:

* go to https://api.us2.sumologic.com/api/ and try to authenticate with your keys - this will tell as if the credentials are indeed valid
* try to remove `sumologic.endpoint` and see if the endpoint autodetection picks up the correct API endpoint

**Comment by pmalek-sumo** [comment]
@ajeetgupt 
Actually there is one thing that should resolve this:
Try adding `/v1` as suffix to the api endpoint: https://api.us2.sumologic.com/api/v1

**Comment by ajeetgupt** [comment]
The above-mentioned api endpoint didn't work for me but this one https://api.us2.sumologic.com/api (removed /) is working fine but I'm still getting the error sharing the screenshot for your reference 
![image](https://user-images.githubusercontent.com/14258969/108865351-2dd31400-7619-11eb-89ca-7e7a56edb6d1.png)
When I try to see the logs of the config error pods I am getting the below output:-
```
kubectl -n sumologic logs pod/sumologic-collection-sumologic-fluentd-events-0
Error from server (BadRequest): container "fluentd-events" in pod "sumologic-collection-sumologic-fluentd-events-0" is waiting to start: CreateContainerConfigError
```
Can you suggest why some of the pods are crashing and some of them are still in pending state?

**Comment by sumo-drosiek** [comment]
@ajeetgupt Could you show us what `kubectl describe` shows about `Pending` and `CreateContainerConfigError` pods?

**Comment by sumo-drosiek** [comment]
For the pending pods. Seems that port for `node-exporter` is already taken, so you need to use another one. You can do it by adding this to the configuration:

```
kube-prometheus-stack:
  prometheus-node-exporter:
    service:
      targetPort: 9200
      port: 9200
```

---

For the configerror pod. I need full `Events:` section (bottom of the last screenshot looks like partially cut but I can be wrong)

**Comment by ajeetgupt** [comment]
There is a single event there  (so the last screenshot having all the events).

**Comment by sumo-drosiek** [comment]
I tried to reproduce the issue with `CreateContainerConfigError` and it occures when `sumologic` secret is not created.
`sumologic` secret should be created by `setup-job`, so this is directly connected to the error from first post.
I checked installation on us2 against two api endpoints: `https://api.us2.sumologic.com/api/` (with slash at the end) and `https://api.us2.sumologic.com/api/`(without slash at the end) and only `https://api.us2.sumologic.com/api/` (with slash at the end) is correct.

For first endpoint (withouy slash), setup job raises error:
```
Error: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404 Not Found</h2>
<table>
<tr><th>URI:</th><td>/v1/collectors</td></tr>
<tr><th>STATUS:</th><td>404</td></tr>
<tr><th>MESSAGE:</th><td>Not Found</td></tr>
<tr><th>SERVLET:</th><td>default</td></tr>
</table>

</body>
</html>
```

---

For invalid credentials i got following error (same like in the issue description)
```
Error: {
  "status" : 401,
  "id" : "7QIIT-4YIC6-17KQ7",
  "code" : "unauthorized",
  "message" : "Credential could not be verified."
}
```

So either you are using invalid API (us2 for non-us2 service) or credentials are invalid. Please check that again and in case it doesn't work, please [contact our support](https://support.sumologic.com/hc/en-us)

**Comment by ajeetgupt** [comment]
Thanks for replying but I have double-checked my credentials and API endpoint using the below two commands:-
Created a pod and pushed a single file.
```
sh sumocollector.sh -q -Vsumo.endpoint=https://api.us2.sumologic.com/api/ -Vsumo.accessid=sxxxxxxxxx3 -Vsumo.accesskey=1pxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx9 -VsyncSources=/opt/sync.json -Vcollector.name=kubernetes -Vclobber=true
```
```
curl -u "sxxxxxxxxxx3:1xxxxxxxxxxxxxxxxxxxxxx" -X GET https://api.us2.sumologic.com/api/v1/users
```
For the first endpoint (without slash [https://api.us2.sumologic.com/api] ), I am getting all the pods and I am attaching the ``` CreateContainerConfigError``` pods events:- 
```
Events:
  Type     Reason          Age                   From               Message
  ----     ------          ----                  ----               -------
  Normal   Scheduled       59m                   default-scheduler  Successfully assigned sumologic/sumologic-collection-sumologic-fluentd-events-0 to ip-10-42-76-68.ec2.internal
  Warning  Failed          58m (x8 over 59m)     kubelet            Error: secret "sumologic" not found
  Normal   SandboxChanged  58m (x8 over 59m)     kubelet            Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          4m5s (x275 over 59m)  kubelet            Container image "public.ecr.aws/sumologic/kubernetes-fluentd:1.12.0-sumo-1" already present on machine
```

For the second endpoint (with slash  [https://api.us2.sumologic.com/api/]) or not passing the endpoint value. I didn't find any pods (batch job kept trying to create pods but was unable to create them)
![image](https://user-images.githubusercontent.com/14258969/109035768-f8005f00-76ee-11eb-9764-dc0d4399f6f8.png)
```
Error: {
  "status" : 401,
  "id" : "LUH9R-BJKZR-ED653",
  "code" : "unauthorized",
  "message" : "Credential could not be verified."
}
  on resources.tf line 1, in resource "sumologic_collector" "collector":
   1: resource "sumologic_collector" "collector" {
```

If you can suggest manually creation of ```sumologic secret``` then I think it will solve the problem.

**Comment by perk-sumo** [comment]
Hi @ajeetgupt!
Which versions of the chart you are using?
Also can please try without providing the endpoint.

If that doesn't work - please [contact our support](https://support.sumologic.com/hc/en-us).

**Comment by ajeetgupt** [comment]
Hi @perk-sumo ,
I am using helm chart version 2.0.3 and I have tried without providing the endpoint, the output is the same as the second endpoint (with slash [https://api.us2.sumologic.com/api/]).

**Comment by emcay** [comment]
Anyone care to share what the fix is for this? I appear to have the same problem.

**Comment by nicholasmhughes** [comment]
I was also receiving this error in the setup container:
```
kubernetes_secret.sumologic_collection_secret: Refreshing state... [id=sumologic/sumologic]
sumologic_collector.collector: Creating...
Error: {
  "status" : 401,
  "id" : "B6GOC-2J3UN-C1UZE",
  "code" : "unauthorized",
  "message" : "Credential could not be verified."
}
  on resources.tf line 1, in resource "sumologic_collector" "collector":
   1: resource "sumologic_collector" "collector" {
Error during applying Terraform changes
```

I ended up working around it with `sumologic.setupEnabled=false` since I was performing an upgrade and the collector was already deployed.

**Comment by pmalek-sumo** [comment]
The reason for this might be that the IP addresses from which the API calls (done by the setup job) are coming from is not added to the [service allowList][allowlist].

We're working on making those errors more visible to the end user. The upcoming release will include #1524 which will log the error coming from the API.

[allowlist]: https://help.sumologic.com/Manage/Security/Create-an-Allowlist-for-IP-or-CIDR-Addresses

**Comment by ajeetgupt** [comment]
Agree with @pmalek-sumo Need to add a public IP (in my case it was natgateway IP) to the service allowlist. 
My issue has been resolved so closing the case !!

**Comment by perk-sumo** [comment]
Unfortunately in this situation (ip not in the allow list) we cannot show the real error because it's not being sent to us.
Hence the cryptic `Credential could not be verified` message.

For the setup job we use the Terraform provider which does not handle all the errors.
There is an issue for that: https://github.com/SumoLogic/terraform-provider-sumologic/issues/110
